pipeline {                                                                       // We are using a declarative pipeline
    agent {                                                                      // We want to use an agent/node
        docker {                                                                 // We want to use docker for this
            image 'public.ecr.aws/docker/library/maven:3.9-sapmachine'           // The docker image to run in
            label 'jenkins-slave'                                                // Use a node/agent with these labels
            args '-u root:sudo'                                                  // Add this to be root in the container
        }
    }
        stages {
        
       stage('Debug Environment') {
            steps {
                sh 'whoami'
                sh 'groups'
                sh 'docker --version'
            }
        } 
        
        stage('Source') {
            steps {
                sh 'mvn --version'
                sh 'git --version'
                git branch: 'main',
                    url: 'https://github.com/LinkedInLearning/essential-jenkins-2468076.git'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}
