pipeline {
    agent { label 'jenkins-slave-label' } // Specify the label of your EC2 agent here
    stages {
        stage('Docker Build and Run') {
            steps {
                script {
                    def dockerImage = 'public.ecr.aws/docker/library/maven:3.9-sapmachine'
            
                    // Pull the Docker image
                    sh "docker pull $dockerImage"
            
                    // Run a Maven installation script inside the container
                    sh "docker run --rm -v ${env.WORKSPACE}:/workspace -w /workspace $dockerImage bash -c 'apt-get update && apt-get install -y maven && mvn --version'"
                    sh "docker run --rm -v ${env.WORKSPACE}:/workspace -w /workspace $dockerImage git --version"
                }
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/Ch04/04_03-docker-agent"){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}
